frontpage:
    path: /
    controller: Kbin\UI\Core\Frontpage\Controller\FrontpageController

# Community
community_create:
    path: /newCommunity
    controller: Kbin\UI\Core\Community\Controller\CreateCommunityController
